<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><meta name="og:site_name" content="Swifty Waves"/><link rel="canonical" href="https://jjorgemoura.github.io/tips/errorHandling"/><meta name="twitter:url" content="https://jjorgemoura.github.io/tips/errorHandling"/><meta name="og:url" content="https://jjorgemoura.github.io/tips/errorHandling"/><title>Error Handling | Swifty Waves</title><meta name="twitter:title" content="Error Handling | Swifty Waves"/><meta name="og:title" content="Error Handling | Swifty Waves"/><meta name="description" content="Tips and Tricks: Swift's Error Handling"/><meta name="twitter:description" content="Tips and Tricks: Swift's Error Handling"/><meta name="og:description" content="Tips and Tricks: Swift's Error Handling"/><meta name="twitter:card" content="summary"/><link rel="stylesheet" href="/styles.css" type="text/css"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><link rel="shortcut icon" href="/images/favicon.png" type="image/png"/><link rel="alternate" href="/feed.rss" type="application/rss+xml" title="Subscribe to Swifty Waves"/></head><body class="item-page"><header><div class="wrapper"><a href="/" class="site-name">Swifty Waves</a><nav><ul><li><a href="/posts">My posts</a></li><li><a href="/tips" class="selected">Tips</a></li><li><a href="/about">Hi! I'm Jorge</a></li></ul></nav></div></header><div class="wrapper"><article><div class="content"><h1>Error Handling</h1><h2>Representing and Throwing Errors</h2><p>In Swift, errors are represented by values of types that conform to the Error protocol. This empty protocol indicates that a type can be used for error handling.</p><p>The common way to modeling a group of related error conditions is with enumerations, with associated values allowing for additional information about the nature of an error to be communicated. Example:</p><pre><code class="language-swift">enum VendingMachineError: Error {
    case invalidSelection
    case insufficientFunds(coinsNeeded: Int)
    case outOfStock
}
</code></pre><p>Throwing an error allows to indicate that something unexpected happened. The way to throw an error is through the <code>throw</code> keyword.</p><pre><code class="language-swift">throw VendingMachineError.insufficientFunds(coinsNeeded: 5)
</code></pre><p>When a method is able to throw and error, that method needs to be declared as a method that can throw an error in order to call site knows and be ready to handle that error. The way to announce that a method can throw an error, the kwyword <code>throws</code> needs to be present in method declaration.</p><pre><code class="language-swift">func canThrowErrors() throws -&gt; String

func cannotThrowErrors() -&gt; String
</code></pre><h2>Handling Errors</h2><p>There are four ways to handle errors in Swift. When a function throws an error, the calling code (function) can handle the potential error in one of four ways:</p><ul><li>propagate the error from a function to the code that calls that function</li><li>handle the error using a do-catch statement</li><li>handle the error as an optional value</li><li>assert that the error will not occur</li></ul><p>The call sites of every throwing function needs to notice that is calling a throwing function and that something need to be done to handler that error. This is achieved by the use of <code>do-catch</code>, <code>try</code>, <code>try?</code> or <code>try!</code>.</p><h3>propagate the error</h3><p>The call function will not handle the error itself, instead, will throw its self and bypass pass the error to its own call function.</p><pre><code class="language-swift">func buyFavoriteSnack(person: String, vendingMachine: VendingMachine) throws {
    let snackName = favoriteSnacks[person] ?? "Candy Bar"
    
    try vendingMachine.vend(itemNamed: snackName)
}
</code></pre><p>So, <strong>propagate the error from a function to the code that calls that function</strong> means the use of <code>try</code> to call a throwing function and mark it self has a <code>throws</code> function.</p><p><strong>Note:</strong> Not only functions are able to throw errors. Initializers (<code>init</code>) can also throw errors.</p><h3>handle the error using a do-catch statement</h3><p>A <code>do-catch</code> statement allows the calling site to handle errors by running a block of code. If an error is thrown by the code in the do clause, it is matched against the catch clauses to determine which one of them can handle the error.</p><pre><code class="language-swift">var vendingMachine = VendingMachine()
vendingMachine.coinsDeposited = 8
do {
    try buyFavoriteSnack(person: "Alice", vendingMachine: vendingMachine)
    print("Success! Yum.")
} catch VendingMachineError.invalidSelection {
    print("Invalid Selection.")
} catch VendingMachineError.outOfStock {
    print("Out of Stock.")
} catch VendingMachineError.insufficientFunds(let coinsNeeded) {
    print("Insufficient funds. Please insert an additional \(coinsNeeded) coins.")
} catch {
    print("Unexpected error: \(error).")
}
// Prints "Insufficient funds. Please insert an additional 2 coins."
</code></pre><p>The order of the <code>catch</code> statements is important. The error is matched with each statement and, as soon as a match is done, the error will be managed.</p><p>So, <strong>handle the error using a do-catch statement</strong> means a thorough error treatment is done. The call site will handle assume and face the treament of the error.</p><p><strong>Note:</strong> A function can have a <code>do-catch</code> block and still decide to throw/propagate the error to its calling site if decides it is not able to handle it.</p><pre><code class="language-swift">func nourish(with item: String) throws {
    do {
        try vendingMachine.vend(itemNamed: item)
    } catch is VendingMachineError {
        print("Couldn't buy that from the vending machine.")
    }
    // Every error that is not a "VendingMachineError" will be thrown to call site.
}
</code></pre><h3>handle the error as an optional value</h3><p>In case we want to considerar an error thrown by function a function as if the function was returning a <code>nil</code> value, an error can be "converted" to an optional value using <code>try?</code>. If an error is thrown while evaluating the try? expression, the value of the expression is nil.</p><pre><code class="language-swift">func someThrowingFunction() throws -&gt; Int {
    // ...
}

let x = try? someThrowingFunction()

let y: Int?
do {
    y = try someThrowingFunction()
} catch {
    y = nil
}
</code></pre><p>So, <strong>handle the error as an optional value</strong> means an error is as if the function is returning an optional.</p><h3>assert that the error will not occur</h3><p>Sometimes, due to the nature of a specific API, we are confident that a throwing function or method wonâ€™t, in fact, throw an error at runtime. On those occasions, we can use <code>try!</code> before the expression to disable error propagation and wrap the call in a runtime assertion that no error will be thrown.</p><p><strong>Note:</strong> Using the <code>try!</code> keyword has a similar effect to <code>Forced Unwrapping</code>. If an error actually is thrown, a runtime error will happen.</p><pre><code class="language-swift">let photo = try! loadImage(atPath: "./Resources/John Appleseed.jpg")
</code></pre><p>In this case, because the image is shipped with the application, no error will be thrown at runtime, so it is appropriate to disable error propagation.</p><p>So, <strong>assert that the error will not occur</strong> means there is confidence an error will never be thown so that possibility is being discarded.</p><h2>Specifying Cleanup Actions</h2><p>If a function needs to perform some "cleaning" after throwing a error, that can be declared through the use for a <code>defer</code> block.</p><pre><code class="language-swift">func processFile(filename: String) throws {
    if exists(filename) {
        let file = open(filename)
        defer {
            close(file)
        }
        while let line = try file.readline() {
            // Work with the file.
        }
        // close(file) is called here, at the end of the scope.
        // This is important to balance with the "open(file)" statement
    }
}
</code></pre><h4>Resources:</h4><p>https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html</p></div><span>Tagged with: </span><ul class="tag-list"><li><a href="/tags/tips">tips</a></li><li><a href="/tags/swift">swift</a></li></ul></article></div><footer><p>Generated using <a href="https://github.com/johnsundell/publish">Publish</a></p><p><a href="/feed.rss">RSS feed</a></p></footer></body></html>